apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackathon-api-ingress
  namespace: fiap-hackathon
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: fiap-hackathon.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hackathon-api
            port:
              number: 80
