apiVersion: v1
kind: Service
metadata:
  name: hackathon-api-service
  namespace: fiap-hackathon
  labels:
    app: hackathon-api
spec:
  selector:
    app: hackathon-api
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: fiap-hackathon
  name: hackathon-db-service
  labels:
    app: hackathon-db
spec:
  type: NodePort
  selector:
    app: hackathon-db
  ports:
    - name: "hackathon-db"
      protocol: TCP
      port: 5432
      targetPort: 5432